<?php

namespace BillTo\PrestaShop\Api;

use BillTo\PrestaShop\Support\Config;
use BillTo\PrestaShop\Support\Logger;
use BillTo\Shop\OAuth\OAuthClient;
use BillTo\Shop\OAuth\TokenSet;

/**
 * OAuth connection state of this shop: the installation's own client credentials and its token
 * pair. Each installation registers its own credentials through Dynamic Client Registration.
 *
 * Token refresh happens here rather than in the API client, so the token is exchanged before a
 * request is sent instead of after it fails.
 */
final class OAuthConnection
{
    const KEY_CLIENT_ID = 'OAUTH_CLIENT_ID';

    const KEY_CLIENT_SECRET = 'OAUTH_CLIENT_SECRET';

    const KEY_ACCESS_TOKEN = 'OAUTH_ACCESS_TOKEN';

    const KEY_REFRESH_TOKEN = 'OAUTH_REFRESH_TOKEN';

    const KEY_EXPIRES_AT = 'OAUTH_EXPIRES_AT';

    const KEY_COMPANY = 'OAUTH_COMPANY';

    /** @var Config */
    private $config;

    /** @var Logger */
    private $logger;

    /** @var OAuthClient */
    private $oauth;

    public function __construct(Config $config, Logger $logger, OAuthClient $oauth)
    {
        $this->config = $config;
        $this->logger = $logger;
        $this->oauth = $oauth;
    }

    public function isConnected(): bool
    {
        return $this->tokens() !== null;
    }

    public function companyName(): string
    {
        return (string) $this->config->get(self::KEY_COMPANY);
    }

    public function clientId(): string
    {
        return (string) $this->config->get(self::KEY_CLIENT_ID);
    }

    public function clientSecret(): string
    {
        return (string) $this->config->get(self::KEY_CLIENT_SECRET);
    }

    /**
     * Registers this installation in BillTo unless it already holds credentials.
     *
     * Idempotent: a repeated call does not create a second client.
     */
    public function ensureRegistered(string $softwareStatementId, string $registrationCode, string $redirectUri, string $installationName): bool
    {
        if ($this->clientId() !== '' && $this->clientSecret() !== '') {
            return true;
        }

        // The software statement id identifies the vendor and ships with the module; the
        // registration code is generated by the merchant in BillTo and is valid for two
        // minutes. Registration requires both.
        $credentials = $this->oauth->register($softwareStatementId, $registrationCode, $installationName, $redirectUri);

        if ($credentials === null) {
            $this->logger->error('[BillTo OAuth] rejestracja instalacji odrzucona przez BillTo');

            return false;
        }

        $this->config->set(self::KEY_CLIENT_ID, $credentials['client_id']);
        $this->config->set(self::KEY_CLIENT_SECRET, $credentials['client_secret']);

        return true;
    }

    /**
     * Exchanges the authorization code for a token pair and stores it. Keeps the installation
     * id and secret in one place, out of the front controller.
     */
    public function exchange(string $code, string $verifier, string $redirectUri): bool
    {
        $tokens = $this->oauth->exchangeCode(
            $this->clientId(),
            $this->clientSecret(),
            $redirectUri,
            $code,
            $verifier
        );

        if ($tokens === null) {
            $this->logger->error('[BillTo OAuth] wymiana kodu autoryzacyjnego odrzucona');

            return false;
        }

        $this->store($tokens);

        return true;
    }

    /**
     * @param array{access_token: string, refresh_token: string|null, expires_in: int} $response
     */
    public function store(array $response, string $companyName = ''): void
    {
        $set = TokenSet::fromTokenResponse($response);

        $this->config->set(self::KEY_ACCESS_TOKEN, $set->accessToken);
        $this->config->set(self::KEY_REFRESH_TOKEN, (string) $set->refreshToken);
        $this->config->set(self::KEY_EXPIRES_AT, (string) $set->expiresAt);

        if ($companyName !== '') {
            $this->config->set(self::KEY_COMPANY, $companyName);
        }
    }

    /**
     * Valid access token, or null when the shop is not connected or the refresh failed.
     *
     * Returns null rather than throwing, so the caller can fall back to a token stored in the
     * configuration by an installation predating OAuth instead of stopping
     * wystawianie faktur.
     */
    public function accessToken(): ?string
    {
        $set = $this->tokens();

        if ($set === null) {
            return null;
        }

        if (!$set->needsRefresh()) {
            return $set->accessToken;
        }

        if (!$set->canRefresh()) {
            // Without a refresh token the shop has to be authorised again by hand, so the
            // state is recorded instead of leaving the caller with repeated 401s.
            $this->logger->error('[BillTo OAuth] token wygasł i nie ma czym go odświeżyć - wymagana ponowna autoryzacja');

            return null;
        }

        $response = $this->oauth->refresh($this->clientId(), $this->clientSecret(), (string) $set->refreshToken);

        if ($response === null) {
            $this->logger->error('[BillTo OAuth] odświeżenie tokenu odrzucone - wymagana ponowna autoryzacja');

            return null;
        }

        // The refresh token is single use: BillTo revokes it during the exchange, so the new
        // pair is stored before the next request.
        $this->store($response);

        return $response['access_token'];
    }

    public function disconnect(): void
    {
        foreach ([self::KEY_ACCESS_TOKEN, self::KEY_REFRESH_TOKEN, self::KEY_EXPIRES_AT, self::KEY_COMPANY] as $key) {
            $this->config->set($key, '');
        }

        // The installation credentials (client_id/secret) are kept: disconnecting withdraws the
        // authorisation for a company, so reconnecting skips registration.
    }

    /**
     * Clears the installation credentials as well.
     *
     * Used when the environment changes: production and sandbox are separate instances with
     * separate client registries, so credentials issued in one are not valid in the other.
     */
    public function forget(): void
    {
        $this->disconnect();

        $this->config->set(self::KEY_CLIENT_ID, '');
        $this->config->set(self::KEY_CLIENT_SECRET, '');
    }

    private function tokens(): ?TokenSet
    {
        return TokenSet::fromArray([
            'access_token' => (string) $this->config->get(self::KEY_ACCESS_TOKEN),
            'refresh_token' => (string) $this->config->get(self::KEY_REFRESH_TOKEN),
            'expires_at' => (int) $this->config->get(self::KEY_EXPIRES_AT),
        ]);
    }
}
